"""Heteronym naming: deriving a name from a Skin, and keeping it on disk safely.

Names reaching this module are generated by an LLM and pasted in by a user, so
they are treated as untrusted input. Everything written to disk goes through
sanitize_heteronym_name(); everything read from disk goes through
safe_character_dir(), which refuses paths that escape the characters directory.
"""

import os
import re

DEFAULT_NAME = "New_Heteronym"
MAX_NAME_LENGTH = 64

# "- **Name**: Foo", "- Handle: **Foo**", "* Street Name: Foo"
# Only horizontal whitespace around the colon: \s* would swallow the newline and
# capture the *next* field's value when a template leaves the field blank.
_FIELD_RE = re.compile(
    r"^[ \t]*[-*+][ \t]*\**[ \t]*(?:name|handle|street[ \t]+name|codename)"
    r"\**[ \t]*:[ \t]*(\S[^\r\n]*)",
    re.IGNORECASE | re.MULTILINE,
)

# First level-1 markdown heading.
_H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)

# Framework decoration around a name in a heading:
# "Stack_And_Dagger - The Skin", "The Skin: Stack_And_Dagger"
_SKIN_SUFFIX_RE = re.compile(r"\s*[—–:-]\s*(?:the\s+)?skin\s*$", re.IGNORECASE)
_SKIN_PREFIX_RE = re.compile(r"^\s*(?:the\s+)?skin\s*[—–:-]\s*", re.IGNORECASE)
_TRAILING_PARENS_RE = re.compile(r"\s*\([^)]*\)\s*$")

# Anything outside this set is replaced; note "." is excluded, so ".." and
# hidden-file names cannot survive.
_UNSAFE_RE = re.compile(r"[^A-Za-z0-9_-]+")

# Reserved device names on Windows.
_RESERVED = {"CON", "PRN", "AUX", "NUL"} | {
    f"{stem}{i}" for stem in ("COM", "LPT") for i in range(1, 10)
}


def sanitize_heteronym_name(raw, default=DEFAULT_NAME):
    """Reduce an arbitrary string to a safe single path segment.

    Strips markdown emphasis, collapses everything outside [A-Za-z0-9_-] to
    underscores and trims separators from the ends. Path separators and dots
    cannot survive, so the result is always a single directory name and never
    "." or "..". Falls back to `default` when nothing usable remains.
    """
    text = (raw or "").strip()
    for token in ("**", "*", "`"):  # underscores are legitimate inside names
        text = text.replace(token, "")

    text = text.replace(" ", "_")
    text = _UNSAFE_RE.sub("_", text)
    text = re.sub(r"_{2,}", "_", text).strip("_-")
    text = text[:MAX_NAME_LENGTH].strip("_-")

    if not text or text.upper() in _RESERVED:
        return default
    return text


def derive_heteronym_name(skin_content, default=DEFAULT_NAME):
    """Best-effort name for a heteronym, read from its Skin.

    Prefers an explicit Name/Handle field, then the H1 heading with framework
    decoration removed ("# Stack_And_Dagger - The Skin" -> "Stack_And_Dagger").
    The result is always sanitized.
    """
    for candidate in _name_candidates(skin_content or ""):
        cleaned = sanitize_heteronym_name(candidate, default="")
        if cleaned:
            return cleaned
    return default


def _name_candidates(skin_content):
    """Yield raw name candidates from a Skin, best first."""
    for match in _FIELD_RE.finditer(skin_content):
        yield match.group(1)

    heading = _H1_RE.search(skin_content)
    if heading:
        text = heading.group(1)
        text = _TRAILING_PARENS_RE.sub("", text)
        text = _SKIN_SUFFIX_RE.sub("", text)
        text = _SKIN_PREFIX_RE.sub("", text)
        yield text


def safe_character_dir(characters_dir, name):
    """Resolve `name` inside `characters_dir`, refusing anything that escapes.

    Applied to names that are *read* (an existing directory the user names) as
    well as written, so a crafted name cannot reach outside the framework.
    Symlinks are resolved, so a symlinked character directory pointing outside
    is rejected too.

    Raises:
        ValueError: if the resolved path is not inside characters_dir.
    """
    if not name or os.path.isabs(name):
        raise ValueError(f"Invalid heteronym name: {name!r}")

    base = os.path.realpath(characters_dir)
    target = os.path.realpath(os.path.join(base, name))

    if target != base and not target.startswith(base + os.sep):
        raise ValueError(
            f"Heteronym name {name!r} resolves outside the characters directory."
        )
    if target == base:
        raise ValueError(f"Invalid heteronym name: {name!r}")
    return target
