import os
import sys
import json
import yaml
from converter import PersonalityConverter

def create_heteronym(name, engine_content, big_five_scores, skin_content=None, seed_content=None):
    """
    Creates a new heteronym folder and populates it with Pessoa Framework files.
    
    Args:
        name (str): Heteronym name.
        engine_content (str): Layer 1: The Engine (Psychological structure).
        big_five_scores (dict): Dictionary of facet scores for Layer 1.
        skin_content (str): Layer 1: The Skin (Biography and Voice).
        seed_content (str): Layer 2: The Seed (Mission and Expertise).
    """
    # Determine target directory relative to this script
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    char_dir = os.path.join(BASE_DIR, "characters", name)
    os.makedirs(char_dir, exist_ok=True)
    
    # 1. Save Engine (Layer 1)
    with open(os.path.join(char_dir, "engine.md"), "w") as f:
        f.write(engine_content)
        
    # 2. Save Big Five Scores (Layer 1)
    with open(os.path.join(char_dir, "big_five.json"), "w") as f:
        json.dump(big_five_scores, f, indent=2)
        
    # 3. Calculate and Save AI Cabinet (Layer 3)
    params = PersonalityConverter.calculate_layer3_params(big_five_scores)
    
    # Build the 5-Pillar System Prompt Architecture
    ai_cabinet = {
        "name": name,
        "parameters": params,
        "system_prompt_architecture": {
            "identity_anchor": "Distilled from engine.md and skin.md",
            "personality_profile": "Calculated from Big Five scores",
            "communication_style": "Defined by Skin voice patterns",
            "capabilities_expertise": "Defined by the Seed",
            "boundaries_constraints": "Defined by the Shadow/Fear in engine.md"
        },
        "status": "ready"
    }
    
    with open(os.path.join(char_dir, "ai_cabinet.yaml"), "w") as f:
        yaml.dump(ai_cabinet, f, sort_keys=False)
        
    # 4. Save Skin (Layer 1)
    if skin_content:
        with open(os.path.join(char_dir, "skin.md"), "w") as f:
            f.write(skin_content)

    # 5. Save Seed (Layer 2)
    if seed_content:
        with open(os.path.join(char_dir, "seed.md"), "w") as f:
            f.write(seed_content)
        
    print(f"Heteronym '{name}' created successfully in {char_dir}")
    print(f"Calculated Parameters: {params}")

if __name__ == "__main__":
    # Example usage for manual ingestion
    if len(sys.argv) < 2:
        print("Usage: python create_heteronym.py <name>")
        # Demo data (The Strategist)
        demo_scores = {'O': 2.3, 'C': 4.7, 'E': 3.0, 'A': 1.8, 'N': 1.2}
        demo_engine = "# The Strategist Engine\n..."
        demo_skin = "# The Strategist Skin\n..."
        demo_seed = "# The Strategist Seed (Mission: Security Analyst)\n..."
        create_heteronym("Strategist_Demo", demo_engine, demo_scores, demo_skin, demo_seed)
    else:
        # In a real scenario, this would read from a temp file generated by Perplexity
        pass
        
